### ISSUE TITLE
flux-app fails to deploy when userConfig is defined

### ISSUE THREAD

**Issue by mproffitt** [giantswarm/flux-app#121]
Flux app fails to deploy if the configmap is defined and flux isn't already deployed into the cluster.

This issue may have come about as a result a fix upstream (see https://github.com/fluxcd/flux2/issues/2351)

When trying to deploy flux-app, users may see the app fail with `invalid-manifest`

```
reason: 'invalid manifest error: (unable to build kubernetes objects from release
      manifest: [unable to recognize "": no matches for kind "Alert" in version "notification.toolkit.fluxcd.io/v1beta1",
      unable to recognize "": no matches for kind "GitRepository" in version "source.toolkit.fluxcd.io/v1beta1",
      unable to recognize "": no matches for kind "Kustomization" in version "kustomize.toolkit.fluxcd.io/v1beta2",
      unable to recognize "": no matches for kind "Provider" in version "notification.toolkit.fluxcd.io/v1beta1"])'
```
Removing `userConfig` allows flux to deploy, after which the `userConfig` can be layered back in.

**Comment by mproffitt** [comment]
This issue is being covered by https://github.com/giantswarm/flux-app/pull/122

**Comment by gianfranco-l** [comment]
this issue will be fixed by this https://github.com/giantswarm/giantswarm/issues/23087
