### ISSUE TITLE
Request to add AGE encryption support for flux

### ISSUE THREAD

**Issue by jgilfoil** [giantswarm/flux-app#134]
Currently the flux-app chart supports adding only [gpg keys](https://github.com/giantswarm/flux-app/blob/93dba4061466a5e7942866c83c51f16ae446ddab/helm/flux-app/templates/source.yaml#L5) for use by flux for encryption/decryption of secrets. I'd like to be able to use [age encryption](https://fluxcd.io/flux/guides/mozilla-sops/#encrypting-secrets-using-age) in our target cluster, the same way we can use [age encryption keys](https://github.com/giantswarm/flexshopper/blob/main/management-clusters/fox/organizations/flex-sandbox/secrets/sandbox.agekey.enc.yaml) in our giantswarm [cluster management repo](https://github.com/giantswarm/flexshopper/blob/f13c8f7475a84e5069eafb3f8ad8cb6a4173dd82/management-clusters/fox/organizations/flex-sandbox/workload-clusters/sandbox.yaml#L10).

**Comment by pipo02mix** [comment]
I am closing this since it is already merge :)
